#
# Let's Chat Settings
#
# See defaults.yml for all available options
#
env: development # development / production
http:
  enable: true
  host: 0.0.0.0 
  port: 5000
https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem
files:
  enable: true
  provider: local
  local:
    dir: uploads
xmpp:
  enable: true
  port: 5222
  domain: 0.0.0.0 
  roomCreation: true
  debug:
    handled: true
    unhandled: true
database:
  uri: mongodb://localhost/letschat
secrets:
  cookie: secretsauce
auth:
  providers: [freepbx-auth]
#  local:
#    enableRegistration: true
private:
  enable: true
  roster: all # online / all
  expire: false # false or number of minutes
